### ISSUE TITLE
Option found multiple times if same occurs in multiple "commands"

### ISSUE THREAD

**Issue by KiranMohan** [cbeust/jcommander#136]
I am trying to use the "command" feature. The application I'm writing  accepts two sets of commands and they have one option in common for specifying a configuration file.
for eg: 
app generate --config `<file>` --otherOption1
app regenerate --config `<file>` --otherOption2

``` java
@Parameters(commandNames={"-g","--generate"} )
class GenerateOption {
    @Parameter(names={"--config"}, required=true, converter=FileConverter.class  )           
    public File configFile;
}

@Parameters(commandNames={"-r","--regenerate"} )
class RegenerateOption {
    @Parameter(names={"--config"}, required=true, converter=FileConverter.class  )           
    public File configFile;
}
```

JCommander however throws an exception saying that it found "--config" multiple times. Is this a bug or am I coding it wrong here?

**Comment by jeremysolarz** [comment]
@cbeust error is still there

```
@Test
  public void multiOptions(){
    @Parameters(commandNames={"-g","--generate"} )
    class GenerateOption {
      @Parameter(names={"--config"}, required=true, converter=FileConverter.class  )
      public File configFile;
    }

    @Parameters(commandNames={"-r","--regenerate"} )
    class RegenerateOption {
      @Parameter(names={"--config"}, required=true, converter=FileConverter.class  )
      public File configFile;
    }

    GenerateOption generateOption = new GenerateOption();
    RegenerateOption regenerateOption = new RegenerateOption();
    JCommander.newBuilder()
            .addObject(generateOption)
            .addObject(regenerateOption)
            .args(new String[]{"-g", "file1.txt"})
            .build();
    Assert.assertNotNull(generateOption.configFile);
  }
```

**Comment by jeremysolarz** [comment]
This throws an exception.

```
com.beust.jcommander.ParameterException: Found the option --config multiple times

	at com.beust.jcommander.JCommander.addDescription(JCommander.java:566)
	at com.beust.jcommander.JCommander.createDescriptions(JCommander.java:534)
	at com.beust.jcommander.JCommander.parse(JCommander.java:302)
	at com.beust.jcommander.JCommander.parse(JCommander.java:287)
	at com.beust.jcommander.JCommander$Builder.build(JCommander.java:1102)
	at com.beust.jcommander.JCommanderTest.multiOptions(JCommanderTest.java:1453)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:696)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:882)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1189)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by cbeust** [comment]
This example is using commands incorrectly by adding the objects as regular option objects, hence the collision. Here is the proper way to do it:

```
        class GenerateOption {
            @Parameter(names={"--config"}, required=true, converter=FileConverter.class  )
            public File configFile;
        }

        class RegenerateOption {
            @Parameter(names={"--config"}, required=true, converter=FileConverter.class  )
            public File configFile;
        }

        GenerateOption generateOption = new GenerateOption();
        RegenerateOption regenerateOption = new RegenerateOption();
        JCommander.newBuilder()
                .addCommand("--generate", generateOption)
                .addCommand("--regenerate", regenerateOption)
                .args(new String[]{"--generate", "--config", "foo"})
                .build();
        Assert.assertNotNull(generateOption.configFile);
```
