### ISSUE TITLE
Commands-Pattern dies by missing annotation.

### ISSUE THREAD

**Issue by migmedia** [cbeust/jcommander#223]
Using [commands-pattern](http://www.jcommander.org/#Complex) without annotate the command-class with `@Parameters()` gives a NullpointerException 

``` stacktrace
Exception in thread "main" java.lang.NullPointerException
    at com.beust.jcommander.JCommander.usage(JCommander.java:1129)
    at com.beust.jcommander.JCommander.usage(JCommander.java:1049)
    at com.beust.jcommander.JCommander.usage(JCommander.java:1041)
    at ...
```

It would be helpfull to get an exception with a hint of this requirement.

**Comment by jeremysolarz** [comment]
@migmedia can you please provide an example

**Comment by jeremysolarz** [comment]
@cbeust I think this is an old issue. Where a NPE was thrown when the description was missing.

Closing it?
