### ISSUE TITLE
Unhelpful message: Class com.beust.jcommander.Parameterized can not access a member of class com.rs.dv.proxy.DvProxyArguments with modifiers ""

### ISSUE THREAD

**Issue by garydgregory** [cbeust/jcommander#231]
This message is unhelpful:

Class com.beust.jcommander.Parameterized can not access a member of class com.rs.dv.proxy.DvProxyArguments with modifiers ""

What member? Does "" mean package private?

Thanks,
Gary

**Comment by cbeust** [comment]
Agreed. Can you include the whole stack trace?

**Comment by garydgregory** [comment]
Voila:

2015-04-13 12:11:08,128 DEBUG [main][io.netty.util.internal.logging.InternalLoggerFactory] Using SLF4J as the default logging framework
DV Proxy 3.1-SNAPSHOT compiled on 2015-04-13T11:33:46 by ggregory (non-jar build)
2015-04-13 12:11:08,193 ERROR [main][com.rs.jdbc.dv.log.DvStaticLogger] catching
com.beust.jcommander.ParameterException: java.lang.IllegalAccessException: Class com.beust.jcommander.Parameterized can not access a member of class com.rs.dv.proxy.DvProxyArguments with modifiers "public"
	at com.beust.jcommander.Parameterized.set(Parameterized.java:194)
	at com.beust.jcommander.WrappedParameter.addValue(WrappedParameter.java:69)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:261)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:210)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:875)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:857)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.rs.dv.proxy.DvProxyArguments.<init>(DvProxyArguments.java:128)
	at com.rs.dv.proxy.DvProxy.<init>(DvProxy.java:67)
	at com.rs.dv.proxy.DvProxy.main(DvProxy.java:39)
Caused by: java.lang.IllegalAccessException: Class com.beust.jcommander.Parameterized can not access a member of class com.rs.dv.proxy.DvProxyArguments with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:109)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:261)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:253)
	at java.lang.reflect.Method.invoke(Method.java:599)
	at com.beust.jcommander.Parameterized.set(Parameterized.java:187)
	... 11 more

**Comment by cbeust** [comment]
Can you trim down your class and include it here so I can reproduce the problem?

**Comment by garydgregory** [comment]
My class is huge.

This should do it:

package test;

class Foo {
   private int bar;
  @Parameter(name="-bar")
   void setBar(int value) {
     bar = value;
  }
}

**Comment by cbeust** [comment]
Should be fixed:

https://github.com/cbeust/jcommander/commit/b359f53dabecff38bb3557dfc35acb378d58019e

**Comment by jeremysolarz** [comment]
@cbeust ready to be closed?
