### ISSUE TITLE
Compatibility with Java 6

### ISSUE THREAD

**Issue by adzubla** [cbeust/jcommander#241]
Running JCommander 1.48 with Java 6 gives this error:

java.lang.NoClassDefFoundError: java/nio/file/Path
	at com.beust.jcommander.internal.DefaultConverterFactory.<clinit>(DefaultConverterFactory.java:66)
	at com.beust.jcommander.JCommander.<clinit>(JCommander.java:167)
....
Caused by: java.lang.ClassNotFoundException: java.nio.file.Path
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 34 more

Commit 495a006cacb2a62449b74474fc57ca2e1b37d85d added a reference to java.nio.file.Path class that is only available in Java 7.

Could this be fixed?

**Comment by cbeust** [comment]
Not without breaking existing clients, so I'd rather not. JDK 6 is no longer supported...

**Comment by robob4him** [comment]
@cbeust Was there ever a version which did? I have a hard dependency on 6 and I'd at least like to use a supported version, if possible.

**Comment by cbeust** [comment]
Not sure...

**Comment by onesuper** [comment]
@robob4him

+1

**Comment by garydgregory** [comment]
-1. Goodbye Java 6.

**Comment by robob4him** [comment]
@cbeust, @onesuper 1.47 did work fine for Java 6 support, FYI.
