### ISSUE TITLE
setAllowAbbreviatedOptions fails on sub-command parameters

### ISSUE THREAD

**Issue by andrewbaxter** [cbeust/jcommander#244]
Demonstration code:

```java
class P1 {}
class P2 {
	@Parameter(names = "--hello")
	private int test;
}
P1 p1 = new P1();
P2 p2 = new P2();
JCommander j = new JCommander(p1);
j.addCommand("wonderful", p2);
j.setAllowAbbreviatedOptions(true);
j.parse(new String[]{"wond", "--he", "47"});
System.out.printf("command %s, test %d\n", j.getParsedCommand(), p2.test);
```

Raises:
```
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: --he
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:791)
	at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	at test.main.main(main.java:24)
```

**Comment by cbeust** [comment]
Thanks for the test case, it does look like an oversight: abbreviated parameters should work for commands too.
