### ISSUE TITLE
Prohibited package name: java.nio.file

### ISSUE THREAD

**Issue by 4ntoine** [cbeust/jcommander#251]
I'm testing with JDK 6 on mac and i'm getting the following error:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
    at com.beust.jcommander.JCommander.<clinit>(JCommander.java:167)
    at Agent.main(Agent.java:116)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.SecurityException: Prohibited package name: java.nio.file
    at java.lang.ClassLoader.preDefineClass(ClassLoader.java:485)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at com.beust.jcommander.internal.DefaultConverterFactory.<clinit>(DefaultConverterFactory.java:66)
    ... 7 more
```

**Comment by TKlerx** [comment]
Yeah, because jcommander is Java 7.

**Comment by cbeust** [comment]
@4ntoine Are you running JCommander with a security manager, by any chance?

**Comment by jeremysolarz** [comment]
@4ntoine any update on this?
Otherwise should be closed.
