### ISSUE TITLE
Build fails using Java 7

### ISSUE THREAD

**Issue by wardev** [cbeust/jcommander#257]
When trying to run the test suite (mvn clean test) I get the following exception
```
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
        at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
        at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: java.lang.UnsupportedClassVersionError: org/testng/TestNG : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:412)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at org.apache.maven.surefire.booter.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:93)
        at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:61)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
        at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
        at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
        ... 9 more
```

It seems that the TestNG library was compiled to only be compatible with Java 8 and above. Is this intentional? Is there a way to build with Java 7?

**Comment by cbeust** [comment]
Travis seems to have no problems building with Java 8, 7 and OpenJDK:

https://travis-ci.org/cbeust/jcommander

Maybe change the TestNG version it's using?

**Comment by wardev** [comment]
From that link all three builds seem to be failing. The Java 8 build due to test failures and the Java 6/7 builds due to an exception caused by using a Java 8 API. For some reason the jobs are still green but the logs all show failures. I think part of the issue is that Kobalt always seems to exit with status 0 independent of the build's actual result.

**Comment by cbeust** [comment]
Indeed, you are completely right. Looking into it.

-- 
Cédric

**Comment by cbeust** [comment]
I made a few changes but still seeing this error for Java 7:

3.79s$ ./kobaltw assemble test
Downloading https://github.com/cbeust/kobalt/releases/download/0.389/kobalt-0.389.zip
100.0%
[Wrapper] Downloaded
https://github.com/cbeust/kobalt/releases/download/0.389/kobalt-0.389.zip
Exception in thread "main" java.lang.NoClassDefFoundError:
java/util/function/Consumer
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at com.beust.kobalt.app.MainModule.configure(MainModule.kt:29)
    at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
    at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
    at com.google.inject.spi.Elements.getElements(Elements.java:110)
    at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
    at com.google.inject.Guice.createInjector(Guice.java:96)
    at com.google.inject.Guice.createInjector(Guice.java:73)
    at com.google.inject.Guice.createInjector(Guice.java:62)
    at com.beust.kobalt.MainKt.mainNoExit(Main.kt:46)
    at com.beust.kobalt.MainKt.main(Main.kt:29)
Caused by: java.lang.ClassNotFoundException: java.util.function.Consumer
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

​

-- 
Cédric

**Comment by wardev** [comment]
Looks like using a Java 8 API that didn't exist in Java 7 from com.beust.kobalt.app.MainModule.configure(MainModule.kt:29)

I'm not familiar with the kt language so I don't think I'll be much help fixing that.

**Comment by jeremysolarz** [comment]
@cbeust because starting from version 1.58 Java 8 is required I guess this can be closed :smile:
