### ISSUE TITLE
Failure while parsing comma seperated enums into List parameter

### ISSUE THREAD

**Issue by bjohnson1417** [cbeust/jcommander#266]
```
public class ArgsEnum {
    enum ChoiceType { ONE, TWO }

    @Parameter(names = "-choices")
    private List<ChoiceType> choices;

    public static void main(String[] args) {
        ArgsEnum argsEnum = new ArgsEnum();
        JCommander jCommander = new JCommander(argsEnum, "-choices", "ONE,TWO");
    }
}
```

Fails with exception:

Exception in thread "main" com.beust.jcommander.ParameterException: Invalid value for -choices parameter. Allowed values:[ONE, TWO]
    at com.beust.jcommander.JCommander.convertValue(JCommander.java:1275)
    at com.beust.jcommander.JCommander.convertValue(JCommander.java:1223)
    at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:242)
    at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:210)
    at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:875)
    at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:857)
    at com.beust.jcommander.JCommander.parseValues(JCommander.java:725)
    at com.beust.jcommander.JCommander.parse(JCommander.java:282)
    at com.beust.jcommander.JCommander.parse(JCommander.java:265)
    at com.beust.jcommander.JCommander.<init>(JCommander.java:210)

**Comment by jeremysolarz** [comment]
@cbeust this is fixed in latest version
