### ISSUE TITLE
Permanent failure on autotest atFileWithInNonDefaultCharset()

### ISSUE THREAD

**Issue by ldelaprade** [cbeust/jcommander#298]
## Test set: TestSuite

Tests run: 183, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.758 sec <<< FAILURE!
atFileWithInNonDefaultCharset(com.beust.jcommander.JCommanderTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
    at org.testng.Assert.fail(Assert.java:94)
    at org.testng.Assert.failNotEquals(Assert.java:494)
    at org.testng.Assert.assertTrue(Assert.java:42)
    at org.testng.Assert.assertTrue(Assert.java:52)
    at com.beust.jcommander.JCommanderTest.atFileWithInNonDefaultCharset(JCommanderTest.java:666)

**Comment by simon04** [comment]
Can you add a breakpoint at `JCommanderTest.java:666` and obtain the stracktrace of the exception?

**Comment by jeremysolarz** [comment]
@ldelaprade any update on this?

**Comment by jeremysolarz** [comment]
@cbeust looks like we can close this.
