### ISSUE TITLE
Exception when running `gradle test` in macos

### ISSUE THREAD

**Issue by jeremysolarz** [cbeust/jcommander#312]
When `gradle test` is run it fails with _BUILD FAILED_ with the following stack trace

```
java.lang.NullPointerException
        at org.gradle.api.internal.tasks.DefaultTaskDependency.add(DefaultTaskDependency.java:144)
        at org.gradle.api.internal.AbstractTask$11.run(AbstractTask.java:351)
        at org.gradle.api.internal.tasks.TaskMutator.mutate(TaskMutator.java:40)
        at org.gradle.api.internal.AbstractTask.dependsOn(AbstractTask.java:349)
        at com.jfrog.bintray.gradle.BintrayPlugin$_apply_closure2_closure5.doCall(BintrayPlugin.groovy:96)
        at com.jfrog.bintray.gradle.BintrayPlugin$_apply_closure2.doCall(BintrayPlugin.groovy:88)
```

using Gradle version 3.2.1

**Comment by jeremysolarz** [comment]
Looks like it has to do with an old version of bintray as defined in 
```
plugins {
    id "com.jfrog.bintray" version "1.1"
}
```

Pumped version 1.1 to 1.2 now it works but TestNG tests are still not executed.

**Comment by jeremysolarz** [comment]
Added

```
test {
    // enable TestNG support (default is JUnit)
    useTestNG()
}
```

as shown in the (docs)[https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html] now it works.
