### ISSUE TITLE
java.lang.reflect.InaccessibleObjectException on Java 9

### ISSUE THREAD

**Issue by triceo** [cbeust/jcommander#341]
JCommander throws the following exception on OpenJDK 9.0.0.154.

java.lang.reflect.InaccessibleObjectException: Unable to make protected final void java.lang.Enum.finalize() accessible: module java.base does not "opens java.lang" to unnamed module @1356d4d4
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:207)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:192)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:186)
	at com.beust.jcommander.Parameterized.parseArg(Parameterized.java:124)
	at com.beust.jcommander.JCommander.addDescription(JCommander.java:541)
	at com.beust.jcommander.JCommander.createDescriptions(JCommander.java:534)
	at com.beust.jcommander.JCommander.addCommand(JCommander.java:1440)
	at com.beust.jcommander.JCommander.addCommand(JCommander.java:1419)
        ...

**Comment by triceo** [comment]
The command objects I supply to `addCommand()` are, in fact, values in an enum.
