### ISSUE TITLE
Boolean parameters flips on multiple parse

### ISSUE THREAD

**Issue by colomb001** [cbeust/jcommander#378]
I looked in the documentation to see if this is intended, but I don't think it is. I recently upgraded from version 1.48 to 1.72 and noticed that boolean parameters would now toggle between true and false when parsed multiple times.

```
public class Parameters
{
    @Parameter(names = {"-f" }, description = "flag" )
    private boolean flagged = false;
}

public void parameterTest()
{
    Parameters parameters = new Parameters();
    JCommander jCommander = new JCommander( parameters );
    jCommander.parse( "-f" );

    Assert.assertTrue( parameters.flagged );

    jCommander.parse( "-f" );

    Assert.assertTrue( parameters.flagged ); //this fails
}
```

**Comment by cbeust** [comment]
Indeed, this was introduced to add support for negative boolean parameters.

I can add a check to make sure that once a boolean parameter is set, it won't get set again.

**Comment by colomb001** [comment]
Negative boolean parameters? Is there an example in the documentation?

**Comment by cbeust** [comment]
I'm not sure I updated the documentation. The idea is simple: you give the
default value to your boolean parameter in your args class and when the
corresponding option is found on the command line, the value of that
parameter is flipped, instead of unconditionally being set to true as was
the case before.


-- 
Cédric

**Comment by email2liyang** [comment]
@cbeust I meet exactly the same issue, is there any way to bypass it?

**Comment by cbeust** [comment]
@email2liyang Can you be more specific? Are you saying you expect something like `-foo -foo -foo` to switch the corresponding boolean field three times? If so, that doesn't seem to be a very intuitive feature.

**Comment by email2liyang** [comment]
@cbeust , I have 2 test cases like below
```
package com.beust.jcommander;

import org.testng.annotations.Test;

/**
 * @author email2liyang@gmail.com
 */
public class BooleanTest {

  @Test
  public void testBoolean() throws Exception {
    class Arg {
      @Parameter(names = { "-v", "--validate" }, description = "if validation is needed")
      private boolean validate = false;
    }
    Arg arg = new Arg();
    JCommander jc = new JCommander(arg);
    jc.parse("-v", "true");
  }

  @Test
  public void testString() throws Exception {
    class Arg {
      @Parameter(names = { "-v", "--validate" }, description = "if validation is needed")
      private String validate = "false";
    }
    Arg arg = new Arg();
    JCommander jc = new JCommander(arg);
    jc.parse("-v", "true");
  }
}
```
* testString works well
* testBoolean will failed with exception
```
com.beust.jcommander.ParameterException: Was passed main parameter 'true' but no main parameter was defined in your arg class

	at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:943)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:750)
	at com.beust.jcommander.JCommander.parse(JCommander.java:342)
	at com.beust.jcommander.JCommander.parse(JCommander.java:321)
	at com.beust.jcommander.BooleanTest.testBoolean(BooleanTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
```

**Comment by anhlt18vn** [comment]
Any update on this issue?

**Comment by cbeust** [comment]
That's expected: boolean parameters have by definition an arity of zero: you only need to pass `-v` to flip it. Any additional parameter will be interpreted further.

If you want to support `-v true`, you need to set its arity to one.

**Comment by sschuberth** [comment]
Just checking, @cbeust: Given (Kotlin) code like

    @Parameter(description = "Enable debug logging and keep any temporary files.",
            names = ["--debug"])
    private var debug = false

are you saying that specifying `--debug --debug` is *intended* to toggle debug to `false` again? I believe that behavior is *very* unintuitive. Because that's the behavior we're seeing with JCommander 1.74.
