### ISSUE TITLE
JSONArray converter always return null

### ISSUE THREAD

**Issue by Moataz-Hammous** [cbeust/jcommander#396]
I have parameter of type JSONArray & i have implemented JSONArray converter but always get the following error 
Could not invoke null
    Reason: Can not set org.json.simple.JSONArray field com.pixelogicmedia.digitalpackage.utils.GeneratorCommand.generationAssets to java.util.ArrayList
	at com.beust.jcommander.Parameterized.set(Parameterized.java:263)
	at com.beust.jcommander.ParameterDescription.addValue(ParameterDescription.java:250)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:895)
	at com.beust.jcommander.JCommander.processFixedArity(JCommander.java:870)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:721)
	at com.beust.jcommander.JCommander.parse(JCommander.java:340)
	at com.beust.jcommander.JCommander.parse(JCommander.java:319)
	at com.pixelogicmedia.digitalpackage.Main.main(Main.java:56)

code take the following path 
 boolean var8 = Collection.class.isAssignableFrom(var6);

**Comment by acostalima** [comment]
@Moataz-Hammous could you post your code?
