### ISSUE TITLE
Regression: NPE when using a Boolean field that has not been initialised

### ISSUE THREAD

**Issue by pvliss** [cbeust/jcommander#447]
Using version 1.72, an NPE is thrown when using a field of type Boolean without initializing it.

This was working normally until version 1.60.

I have not checked against other versions

## Test case
Here's a simple test case that should otherwise work:

```
import com.beust.jcommander.JCommander;
import com.beust.jcommander.Parameter;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

public class TestNPE {

    public static final String PARAM_NAME = "--refresh"; //NOI18N

    @Test
    public void testBooleanWithoutDefaultValue() {
        CmdArgs args = new CmdArgs();
        JCommander commander = new JCommander(args);
        commander.setAcceptUnknownOptions(true);
        commander.parse(PARAM_NAME);
        
        assertTrue(args.m_refresh);
    }

    public static class CmdArgs {

        @Parameter(names = PARAM_NAME)
        private Boolean m_refresh;
    }

}

```
but fails with the following exception:
```
java.lang.NullPointerException
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:718)
	at com.beust.jcommander.JCommander.parse(JCommander.java:340)
	at com.beust.jcommander.JCommander.parse(JCommander.java:319)
	at TestNPE.testBooleanWithoutDefaultValue(TestNPE.java:20)
        ...
```

## Workarounds:
1. Initialize field to false
2. Switch to using boolean instead

**Comment by shaburov** [comment]
Error in Parameterized.get (Object object)
![image](https://user-images.githubusercontent.com/15269131/44948907-5f473c00-ae2f-11e8-8d78-7a56575905eb.png)

**Comment by mageddo** [comment]
same here

**Comment by shaburov** [comment]
@pvliss @mageddo 
```
<repositories>
    <repository>
        <id>spring.plugins.repository</id>
        <url>http://repo.spring.io/plugins-release/</url>
    </repository>
</repositories>
```
and use version 1.74+
```
<dependency>
    <groupId>com.beust</groupId>
    <artifactId>jcommander</artifactId>
    <version>1.74</version>
</dependency>
```
