### ISSUE TITLE
kobaltw is broken

### ISSUE THREAD

**Issue by mkarg** [cbeust/jcommander#488]
Kobaltw seems to be broken:
```bash
$ ./kobaltw assemble test
[Wrapper error] *** No file to download. Server replied HTTP code: 404
[Wrapper error] *** No file to download. Server replied HTTP code: 404
[Wrapper error] *** No file to download. Server replied HTTP code: 404
Exception in thread "main" java.io.FileNotFoundException: /home/travis/.kobalt/wrapper/dist/kobalt-1.0.112.zip (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at com.beust.kobalt.wrapper.Main.extractZipFile(Main.java:335)
	at com.beust.kobalt.wrapper.Main.installDistribution(Main.java:188)
	at com.beust.kobalt.wrapper.Main.installAndLaunchMain(Main.java:81)
	at com.beust.kobalt.wrapper.Main.main(Main.java:17)
The command "./kobaltw assemble test" exited with 1.
```

**Comment by mkarg** [comment]
@cbeust Any idea?

**Comment by cbeust** [comment]
Should be fixed, thanks for the report!

**Comment by mkarg** [comment]
> Should be fixed, thanks for the report!

Works like a charm, thanks! :-)
