### ISSUE TITLE
Required password always complains that it is not specified

### ISSUE THREAD

**Issue by RobertLarsen** [cbeust/jcommander#97]
``` java
import com.beust.jcommander.Parameter;
import com.beust.jcommander.JCommander;

public class Test {
    private static class CommandLineArguments {
        @Parameter (names={"--certificate", "-c"}, description="Path to PKCS12 certificate file", required=true)
        public String filepath;
        @Parameter (names={"--password", "-p"}, description="Private key password", password=true, required=true)
        public String password;
        @Parameter (names={"--port", "-o"}, description="Port to bind server to", required=true)
        public int port;

        public String toString() {
            return "Path: " + filepath + " Password: " + password + " Port: " + port;
        }
    }

    public static void main (String args[]) throws Exception {
        CommandLineArguments arguments = new CommandLineArguments();
        new JCommander(arguments, args);
        System.out.println(arguments);
    }
}
```

Results in this:

``` bash
$ java -jar test.jar --port 7 --certificate cert.p12 --password
Private key password: 
Exception in thread "main" com.beust.jcommander.ParameterException: The following options are required: --password, -p 
    at com.beust.jcommander.JCommander.validateOptions(JCommander.java:308)
    at com.beust.jcommander.JCommander.parse(JCommander.java:275)
    at com.beust.jcommander.JCommander.parse(JCommander.java:257)
    at com.beust.jcommander.JCommander.<init>(JCommander.java:202)
    at Test.main(Test.java:20)
```

**Comment by jeremysolarz** [comment]
This is fixed in the latest version.
